// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4079.DeepSpace.subsystems;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.cameraserver.CameraServer;

import org.opencv.core.Mat;

import edu.wpi.cscore.AxisCamera;
import edu.wpi.cscore.CvSink;
import edu.wpi.cscore.CvSource;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Camera extends Subsystem {

    Thread m_axisCamThread;

    public Camera() {
        m_axisCamThread = new Thread(() -> {
            AxisCamera axisCamera = CameraServer.getInstance().addAxisCamera("axis-camera.local");
            axisCamera.setResolution(640, 480);
      
            CvSink cvSink = CameraServer.getInstance().getVideo();
            CvSource cvSource = CameraServer.getInstance().putVideo("Rectangle", 640, 480);
      
            Mat mat = new Mat();
            while (!Thread.interrupted()) {
              if (cvSink.grabFrame(mat) == 0) {
                cvSource.notifyError(cvSink.getError());
                continue;
              }
      
              cvSource.putFrame(mat);
            }
          });
          
          m_axisCamThread.setDaemon(true);
          m_axisCamThread.start();
    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
       // setDefaultCommand(new StreamVideo());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop
        
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

  
}

