// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc4079.DeepSpace.commands;

import edu.wpi.first.wpilibj.command.InstantCommand;

import org.usfirst.frc4079.DeepSpace.Constants;


/**
 *
 */
public class CycleLiftState extends InstantCommand {
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public CycleLiftState() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        switch(Constants.kLiftState){
            case 12: {
                Constants.kLiftState=13;
                Constants.kLiftDuration=3;
            }
            case 13: {
                Constants.kLiftState=20;
                Constants.kLiftDuration=1.5;
            }
            case 20: {
                Constants.kLiftState=23;
                Constants.kLiftDuration=2;
            }
            case 23: {
                Constants.kLiftState=12;
                Constants.kLiftDuration=1;
            }
        }
         
    }

}